name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images for Each Folder
        run: |
          # Loop through all directories and build images using their folder names
          for dir in $(find . -maxdepth 1 -type d ! -name '.' ! -name '.git' ! -name '.github'); do
            image_name=$(basename "$dir")
            echo "Building image for folder: $image_name"
            
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${image_name}:latest $dir
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/${image_name}:latest
          done
