name: docker build

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'name'
        required: true
        default: ''
      image_tag:
        description: 'tag'
        required: true
        default: ''

permissions:
  packages: write
  contents: read
  attestations: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    # ---
    steps:
    - uses: actions/checkout@v4
    # ---
    - uses: docker/setup-buildx-action@v3
    # ---
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # ---
    - uses: docker/build-push-action@v6
      with:
        context: ${{ github.workspace }}/${{ github.event.inputs.image_name }}
        file: ${{ github.workspace }}/${{ github.event.inputs.image_name }}/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}