name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images for Each Folder
        run: |
          for dir in $(find . -maxdepth 1 -type d ! -name '.' ! -name '.git' ! -name '.github'); do
            image_name=$(basename "$dir")
            echo "Building image for folder: $image_name"
            
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${image_name}:latest $dir
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/${image_name}:latest

            if [ -f "$dir/README.md" ]; then
              echo "Uploading README.md for $image_name"
              
              curl -X PATCH "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/${image_name}/" \
                -H "Authorization: JWT ${{ secrets.DOCKERHUB_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d "{\"full_description\": \"$(jq -sR . < \"$dir/README.md\")\"}"
            else
              echo "No README.md found for $image_name"
            fi
          done

      - name: Log out of Docker Hub
        run: docker logout
